### ISSUE TITLE
[Publish] Python Community 9 Sept 2022

### ISSUE THREAD

**Issue by kjaymiller** [kjaymiller/Python-Community-News#104]
### Use this checklist to walk through all the steps you'll need to complete for each episode

- [ ] Download the Audio/Video from StreamYard
- [ ] Share the YouTube link with folks on social media
- [ ] Break the video into chapters
- [ ] Update Timestamps in Shownotes Post
- [ ] Publish podcast episode
- [ ] Add Github link/podcast url/and YouTube link to content

### Episode Date

2022-09-02

### Shownotes ID

052fe328

### YouTube ID

DqVF1_MSFwQ

### Issues

#TODO

### Newsletter Publish Date/Time

2022-09-12T06:00-08:00
